OS_NAME_LINUX   = 'Linux'
OS_NAME_MACOS   = 'Darwin'
OS_NAME_WINDOWS = 'Windows'

FILE_SEPARATOR_LINUX = '/'
FILE_SEPARATOR_WINDOWS = '\\'
FILE_SEPARATORS = [FILE_SEPARATOR_LINUX, FILE_SEPARATOR_WINDOWS]

NEWLINE_LINUX = '\n'
NEWLINE_WINDOWS = '\r\n'

PATH_SEPARATOR_LINUX = ':'
PATH_SEPARATOR_WINDOWS = ';'
PATH_SEPARATORS = [PATH_SEPARATOR_LINUX, PATH_SEPARATOR_WINDOWS]

